name: PortakalWelcomer
version: '1.0-Slotted'
main: org.noobfly.portakalwelcomer.PortakalWelcomer
api-version: '26.2'
folia-supported: true
description: Ilk giris tanitim sinematigi.
depend: [packetevents]

commands:
  portakalwelcomer:
    description: Tanitim ve kamera testleri.
    usage: /portakalwelcomer <tanitim [oyuncu]|kilit|sinematik|olum|birak [oyuncu]>
    aliases: [pwc]
    permission: portakalwelcomer.admin

permissions:
  portakalwelcomer.admin:
    description: PortakalWelcomer test komutunu kullanma yetkisi.
    default: op
